cargo-features = ["edition2024"]

[package]
name = "BPE"
version = "0.1.0"
edition = "2024"


[dependencies]
indicatif = "0.17.11"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
